version: '3.1'

services:
  back-user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: dev
    ports:
      - '8086:8086'

networks:
  default:
    external:
      name: connect-default